# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найменшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (1), (30, 56, 25), (10, 20), (33, ), (40,), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [5]:
lst = [(10, 20), (1), (30, 56, 25), (10, 20), (33, ), (40,), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]

def minid_tplist(tplist):
    def tp_sum(tupl):
        if isinstance(tupl, int):
            return tupl
        else:
            return sum(tupl)
    idx = 0
    min_sum = tp_sum(tplist[0])
    for i, tup in enumerate(tplist):
        curr_sum = tp_sum(tup)
        if curr_sum < min_sum:
            min_sum = curr_sum
            idx = i
    return idx

minid_tplist(lst)

1

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [6]:
import re
def texttodict(in_str):
    list_str = re.split('[^a-z]', in_str.strip('\n\r.').lower())
    list_str = list(filter(None, list_str)) 
    set_str = set(list_str)
    dict_str = {ke:list_str.count(ke) for ke in set_str}
    return dict_str

text = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."

texttodict(text)

{'also': 1,
 'analytics': 1,
 'as': 1,
 'data': 1,
 'deriving': 1,
 'equivalent': 1,
 'from': 1,
 'high': 1,
 'information': 1,
 'is': 1,
 'mining': 2,
 'of': 1,
 'process': 1,
 'quality': 1,
 'referred': 1,
 'roughly': 1,
 'text': 4,
 'the': 1,
 'to': 2}

### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле, N > 0). Кожен наступний день він зменшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50) до тих пір, коли дистанція пробігу за день стала меншою, ніж N / R (R - ціле, 0 < R < N, N / R - дійсне), після цього дня спортсмен збільшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня, до тих пір, коли дистанція за день стала більшою, ніж N**R . Після цього дня виконувалось початкове правило, тобто дистанція зменшувалась до N/R, а потім збільшувалась до N**R за вищеописаним циклічним законом. По заданим Р, N, M, R, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 10хв
```

In [7]:
def sport_task(N, P, R, M):
    count = 0
    km = 0 # пробіг
    step = N
    while km <= M:
        km += step
        count += 1
        if step > N/R:
            step *= (1-P/100)
        elif step < N*R:
            step *= (1+P/100)
    return count

N = 2
P = 50
M = 5
R = 2

K = sport_task(N, P, R, M)
K

4

### 4. Реалізуйте клас Torus, який створюється за двома радіусами r, R, R > r. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

In [9]:
from math import pi
class Torus:
    def __init__(self, r, R):
        if R < r:
            raise Exception('Thorus with these parameters cannot exist.')
        self.r = r
        self.R = R
    
    def square(self):
        return (2*pi)**2 * self.R * self.r
    
    def volume(self):
        return 2* (pi*self.r)**2 * self.R
    
one = Torus(4, 10)
one.square(), one.volume()
#two = Torus(10, 4)        

(1579.1367041742974, 3158.273408348595)

### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 10хв
```

In [10]:
def log(func):
    def func_wrapper(*args, **kwargs):
        print(f'You called {func.__name__}(', end='')
        for i in args:
            print(i, end=', ')
        klst = []
        for key, val in zip(kwargs.keys(), kwargs.values()):
            klst.append(f'{key}={val}')
        print(*klst, sep=', ', end=')\n')
        try:
            ret = func(*args, **kwargs)
        except Exception as e:
            print(f'It Raised {type(e).__name__}.')
        else:
            print(f'It returned {ret}.')
        
    return func_wrapper

@log
def my_func(*args, **kwargs):
    return sum(args)

my_func(4, 4, '4', kek=4, lol=5)

You called my_func(4, 4, 4, kek=4, lol=5)
It Raised TypeError.


## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного стовпчику від кожного елементу у відповідному стовпчику:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [11]:
import numpy as np

In [13]:
A = np.matrix("17 24 1 8 15 ; 23 5 7 14 16 ; 4 6 13 20 22 ; 10 12 19 21 3 ; 11 18 25 2 9")
A - A.mean(axis=0)

matrix([[  4.,  11., -12.,  -5.,   2.],
        [ 10.,  -8.,  -6.,   1.,   3.],
        [ -9.,  -7.,   0.,   7.,   9.],
        [ -3.,  -1.,   6.,   8., -10.],
        [ -2.,   5.,  12., -11.,  -4.]])

### 7. Дано наступну матрицю:
\begin{align}
B = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}


In [14]:
str_b = """
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0""".replace('\n' , '').replace(' ', '').replace('&', ' ').replace('\\', '; ')
B = np.matrix(str_b)
B

matrix([[  1,  24,   1,   8,  15],
        [ -3,   5,   7, -14,  16],
        [  4,   6,  -3,  20,   2],
        [ 10,  12,  19,  21,   3],
        [  1,   1,   2,  -2,   0]])

#### 7.1. Знайдіть найближче значення в матриці B до будь-якого довільно заданого скаляра.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бал
Рекомендований час: 2хв
```

In [15]:
scal = np.random.uniform(-15, 22, size=None)
scal

-6.333169772461114

In [16]:
diff_B = np.abs(B-scal)
ind = np.unravel_index(diff_B.argmin(), diff_B.shape)
B[ind]

-3

#### 7.2. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [17]:
np.putmask(B, (B > 3) & (B < 16), -B)
B

matrix([[  1,  24,   1,  -8, -15],
        [ -3,  -5,  -7, -14,  16],
        [ -4,  -6,  -3,  20,   2],
        [-10, -12,  19,  21,   3],
        [  1,   1,   2,  -2,   0]])

### 8. Створіть випадковий вектор розміру 20 і замініть мінімальне за модулем значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [18]:
v_rand = np.random.randint(1, 10, size=20)
v_rand[v_rand.argmax()] = 0
v_rand

array([0, 4, 5, 1, 3, 3, 4, 9, 1, 4, 3, 3, 5, 7, 9, 1, 4, 8, 9, 5])

### Pandas

### 9. Розглянемо наступний словник ```data``` та список ```labels```:

In [19]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 9.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [20]:
import pandas as pd

In [34]:
df = pd.DataFrame(data, index=labels)

#### 9.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [22]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


#### 9.3. Поверніть перші 5 рядків ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [23]:
df.head(5)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2

#### 9.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [25]:
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 9.5 Виберіть дані з рядків ```[1, 5, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [26]:
df[['animal', 'age']].iloc[[1, 5, 8]]

animal  age
b    cat  3.0
f    cat  2.0
i    dog  7.0

#### 9.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [27]:
df[df.visits >= 3]

age animal priority  visits
b  3.0    cat      yes       3
d  NaN    dog      yes       3
f  2.0    cat       no       3

#### 9.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [28]:
df[df.age.isnull()]

age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1

#### 9.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [29]:
df[(df.animal == 'cat') & (df.age >=2)]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
f  2.0    cat       no       3

#### 9.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [30]:
df.groupby(by='animal').age.mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

#### 9.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [31]:
df.sort_values(['age', 'visits'], ascending=[False, True])

age animal priority  visits
i  7.0    dog       no       2
e  5.0    dog       no       2
g  4.5  snake       no       1
j  3.0    dog       no       1
b  3.0    cat      yes       3
a  2.5    cat      yes       1
f  2.0    cat       no       3
c  0.5  snake       no       2
h  NaN    cat      yes       1
d  NaN    dog      yes       3

#### 9.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [35]:
d = {'yes':True, 'no':False}
df.priority.replace(d, inplace=True)
df

age animal  priority  visits
a  2.5    cat      True       1
b  3.0    cat      True       3
c  0.5  snake     False       2
d  NaN    dog      True       3
e  5.0    dog     False       2
f  2.0    cat     False       3
g  4.5  snake     False       1
h  NaN    cat      True       1
i  7.0    dog     False       2
j  3.0    dog     False       1

## Scipy & Matplotlib

### 10. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 10.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```