# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найбільшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (40), (30, 56, 25), (10, 20), (33), (40), (42), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [1]:
lst = [(10, 20), (40), (30, 56, 25), (10, 20), (33), (40), (42), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]

def maxid_tplist(tplist):
    def tp_sum(tupl):
        if isinstance(tupl, int):
            return tupl
        else:
            return sum(tupl)
    idx = 0
    max_sum = 0
    for i, tup in enumerate(tplist):
        curr_sum = tp_sum(tup)
        if curr_sum > max_sum:
            max_sum = curr_sum
            idx = i
    return idx

maxid_tplist(lst)

2

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [3]:
import re
def texttodict(in_str):
    list_str = re.split('[^a-z]', in_str.strip('\n\r.').lower())
    list_str = list(filter(None, list_str)) 
    set_str = set(list_str)
    dict_str = {ke:list_str.count(ke) for ke in set_str}
    return dict_str

text = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."

texttodict(text)

{'a': 1,
 'addition': 1,
 'along': 1,
 'also': 1,
 'analytics': 1,
 'and': 6,
 'as': 2,
 'combination': 1,
 'data': 2,
 'database': 1,
 'derived': 2,
 'deriving': 2,
 'devising': 1,
 'equivalent': 1,
 'evaluation': 1,
 'features': 1,
 'finally': 1,
 'from': 1,
 'high': 3,
 'in': 1,
 'information': 2,
 'input': 1,
 'insertion': 1,
 'interestingness': 1,
 'interpretation': 1,
 'into': 1,
 'involves': 1,
 'is': 2,
 'learning': 1,
 'linguistic': 1,
 'means': 1,
 'mining': 4,
 'novelty': 1,
 'of': 7,
 'others': 1,
 'output': 1,
 'parsing': 1,
 'pattern': 1,
 'patterns': 2,
 'process': 2,
 'quality': 3,
 'referred': 1,
 'refers': 1,
 'relevance': 1,
 'removal': 1,
 'roughly': 1,
 'some': 2,
 'statistical': 1,
 'structured': 1,
 'structuring': 1,
 'subsequent': 1,
 'such': 1,
 'text': 7,
 'the': 8,
 'through': 2,
 'to': 3,
 'trends': 1,
 'typically': 1,
 'usually': 3,
 'with': 1,
 'within': 1}

### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле). Кожен наступний день він збільшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50). По заданим Р, N, M, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

In [80]:
def sport_task(N, P, M):
    count = 0
    km = 0 # пробіг
    while km <= M:
        km += N
        count += 1
        N *= (1+P/100)
    return count, km

N = 2
P = 50
M = 3

K = sport_task(N, P, M)
K

(2, 5.0)

### 4. Реалізуйте клас під назвою Triangle, побудований за трьома сторонами та містить два методи: обчислення площі та периметру.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [13]:
from math import sqrt

class Triangle:
    def __init__(self, a, b, c):
        if a + b < c or a + c < b or b + c < a:
            raise Exception('Сума якихось двох сторін більша за третю.')
        self.s1 = a
        self.s2 = b
        self.s3 = c
        
    def get_perimeter(self):
        return self.s1 + self.s2 + self.s3
    
    def get_square(self):
        p = self.get_perimeter()/2
        return sqrt(p*(p-self.s1)*(p-self.s2)*(p-self.s3))
    
    
one = Triangle(4, 3, 5)

one.get_perimeter(), one.get_square()

(12, 6.0)

### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

In [94]:
def log(func):
    def func_wrapper(*args, **kwargs):
        print(f'You called {func.__name__}(', end='')
        for i in args:
            print(i, end=', ')
        klst = []
        for key, val in zip(kwargs.keys(), kwargs.values()):
            klst.append(f'{key}={val}')
        print(*klst, sep=', ', end=')\n')
        try:
            ret = func(*args, **kwargs)
        except Exception as e:
            print(f'It Raised {type(e).__name__}.')
        else:
            print(f'It returned {ret}.')
        
    return func_wrapper

@log
def my_func(*args, **kwargs):
    return sum(args)

my_func(4, 4, '4', kek=4, lol=5)

You called my_func(4, 4, 4, kek=4, lol=5)
It Raised TypeError


## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного рядку від кожного елементу у відповідному рядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [15]:
import numpy as np

In [25]:
A = np.matrix("17 24 1 8 15 ; 23 5 7 14 16 ; 4 6 13 20 22 ; 10 12 19 21 3 ; 11 18 25 2 9")
A - A.mean(axis=1)

matrix([[  4.,  11., -12.,  -5.,   2.],
        [ 10.,  -8.,  -6.,   1.,   3.],
        [ -9.,  -7.,   0.,   7.,   9.],
        [ -3.,  -1.,   6.,   8., -10.],
        [ -2.,   5.,  12., -11.,  -4.]])

### 7. Дано наступні матриці:
\begin{align}
A = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}
\begin{align}
B = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. $(A B)^{-1}B$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [43]:
A = np.matrix("1  24  1  8  15 ; -3  5  7  -14  16 ; 4  6  -3  20  2 ; 10  12  19  21  3 ; 1  1  2  -2  0")
B = np.matrix("17  24  1  8  15 ;    23  5  7  14  16 ;    4  6  13  20  22 ;    10  12  19  21  3 ;    11  18  25  2  9")

AB = np.dot(A, B)
AB_inv = np.linalg.inv(AB)
AB_inv_B = np.dot(AB_inv, B)
AB_inv_B

matrix([[  2.65735362e-02,   1.27035072e-01,   4.97181638e-02,
          -5.77501566e-02,   2.16197802e-02],
        [  4.97822089e-01,   6.94421157e-01,   1.22016431e+00,
           3.15403282e-01,   6.82352226e-01],
        [ -2.73954893e-01,  -5.02742447e-01,  -7.53275932e-01,
          -7.86478909e-02,  -3.21387720e-01],
        [ -1.85941514e-01,  -2.21032323e-01,  -3.40093737e-01,
          -8.74263642e-02,  -2.26374491e-01],
        [  6.39996550e-02,   7.31526811e-02,   9.64328864e-02,
          -4.50602455e-03,   5.30395121e-04]])

#### 7.2. Детермінант: $\det ((A B)^{-1}B)$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [28]:
np.linalg.det(AB_inv_B)

-9.3840321309260041e-06

#### 7.3. Нормалізуйте: $(A B)^{-1}B$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [32]:
arr_norm = (AB_inv_B - AB_inv_B.mean()) / AB_inv_B.std()
arr_norm

matrix([[-0.01505933,  0.23417466,  0.04235994, -0.22425712, -0.02734905],
        [ 1.15405637,  1.64179699,  2.94610779,  0.70149543,  1.6118553 ],
        [-0.76063723, -1.32823393, -1.94977989, -0.27610209, -0.87831285],
        [-0.54228574, -0.62934217, -0.92472041, -0.29788052, -0.6425955 ],
        [ 0.07779074,  0.10049839,  0.15825401, -0.0921643 , -0.07966949]])

#### 7.4. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [48]:
np.putmask(B, (B < 16) & (B> 3), -B)
B

matrix([[ 17,  24,   1,  -8, -15],
        [ 23,  -5,  -7, -14,  16],
        [ -4,  -6, -13,  20,  22],
        [-10, -12,  19,  21,   3],
        [-11,  18,  25,   2,  -9]])

### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [51]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [49]:
import pandas as pd

In [73]:
df = pd.DataFrame(data, index=labels)

#### 8.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [54]:
df.describe(), df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


(            age     visits
 count  8.000000  10.000000
 mean   3.437500   1.900000
 std    2.007797   0.875595
 min    0.500000   1.000000
 25%    2.375000   1.000000
 50%    3.000000   2.000000
 75%    4.625000   2.750000
 max    7.000000   3.000000, None)

#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [55]:
df.head(3)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [56]:
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [57]:
df[['animal', 'age']].iloc[[3, 4, 8]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [58]:
df[df.visits >= 3]

age animal priority  visits
b  3.0    cat      yes       3
d  NaN    dog      yes       3
f  2.0    cat       no       3

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [60]:
df[df.age.isnull()]

age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1

#### 8.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [61]:
df[(df.animal == 'cat') & (df.age >= 2)]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
f  2.0    cat       no       3

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [64]:
df.groupby(by='animal').age.mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [65]:
df.sort_values(['age', 'visits'], ascending=[False, True])

age animal priority  visits
i  7.0    dog       no       2
e  5.0    dog       no       2
g  4.5  snake       no       1
j  3.0    dog       no       1
b  3.0    cat      yes       3
a  2.5    cat      yes       1
f  2.0    cat       no       3
c  0.5  snake       no       2
h  NaN    cat      yes       1
d  NaN    dog      yes       3

#### 8.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

In [77]:
d = {'yes':True, 'no':False}
df.priority.replace(d, inplace=True)
df

age animal  priority  visits
a  2.5    cat      True       1
b  3.0    cat      True       3
c  0.5  snake     False       2
d  NaN    dog      True       3
e  5.0    dog     False       2
f  2.0    cat     False       3
g  4.5  snake     False       1
h  NaN    cat      True       1
i  7.0    dog     False       2
j  3.0    dog     False       1

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати функцію розподілу ймовірностей для вибірок, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Для виібрки з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Для вибірки з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Для вибірки з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Для вибірки з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```